#ifndef ENUMS_H
#define ENUMS_H

/**
 * Tipos de datos del lenguaje
 * */
typedef enum Tipo_Dato { TIPO_INTEGER, TIPO_FLOAT, TIPO_BOOLEAN, TIPO_VOID } TipoDato;

typedef enum Tipo_simbolo {
  SIMBOLO_INTEGER_LITERAL,
  SIMBOLO_FLOAT_LITERAL,
  SIMBOLO_BOOLEAN_LITERAL,
  SIMBOLO_IDENTIFICADOR,
  SIMBOLO_MAIN,
  SIMBOLO_VOID,
  SIMBOLO_RETURN,
  SIMBOLO_SUMA,
  SIMBOLO_MULTIPLICACION,
  SIMBOLO_MOD,
  SIMBOLO_RESTA,
  SIMBOLO_DIV,
  SIMBOLO_ASIGNACION,
  SIMBOLO_IF,
  SIMBOLO_ELSE,
  SIMBOLO_WHILE,
  SIMBOLO_AND,
  SIMBOLO_OR,
  SIMBOLO_NOT,
  SIMBOLO_MAYOR,
  SIMBOLO_MENOR,
  SIMBOLO_IGUALDAD,
  SIMBOLO_VAR_DECL,
  SIMBOLO_MET_DECL
} TipoSimbolo;
#endif
